//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400")]
    public interface ZPM_RFC_CONSUMI_TELEMETRIA_400
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZPM_RFC_CONSUMI_TELEMETRIA_400:Z" +
            "pmRfcConsumiTelemetria400Request", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZPM_RFC_CONSUMI_TELEMETRIA_400:Z" +
            "pmRfcConsumiTelemetria400Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.ZpmRfcConsumiTelemetria400Response1> ZpmRfcConsumiTelemetria400Async(ServiceReference.ZpmRfcConsumiTelemetria400Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZpmRfcConsumiTelemetria400
    {
        
        private ZgeTelCassaItem[] posizioneField;
        
        private ZgeTelCassaHeader testataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZgeTelCassaItem[] Posizione
        {
            get
            {
                return this.posizioneField;
            }
            set
            {
                this.posizioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZgeTelCassaHeader Testata
        {
            get
            {
                return this.testataField;
            }
            set
            {
                this.testataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgeTelCassaItem
    {
        
        private string productField;
        
        private int salesField;
        
        private int testField;
        
        private int refundField;
        
        private decimal prezzoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Sales
        {
            get
            {
                return this.salesField;
            }
            set
            {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Refund
        {
            get
            {
                return this.refundField;
            }
            set
            {
                this.refundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Prezzo
        {
            get
            {
                return this.prezzoField;
            }
            set
            {
                this.prezzoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgeTelError
    {
        
        private string typeField;
        
        private string numberField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZgeTelCassaHeader
    {
        
        private string mandtGwField;
        
        private string codeMaField;
        
        private string odmTaskPalmareField;
        
        private string idTelemetriaField;
        
        private string dateBField;
        
        private string tipoDaField;
        
        private string canaleGettoneField;
        
        private string canaleProveField;
        
        private decimal ch1Field;
        
        private int qty1Field;
        
        private decimal ch2Field;
        
        private int qty2Field;
        
        private decimal ch3Field;
        
        private int qty3Field;
        
        private decimal ch4Field;
        
        private int qty4Field;
        
        private decimal ch5Field;
        
        private int qty5Field;
        
        private decimal ch6Field;
        
        private int qty6Field;
        
        private decimal ch7Field;
        
        private int qty7Field;
        
        private decimal ch8Field;
        
        private int qty8Field;
        
        private decimal ch9Field;
        
        private int qty9Field;
        
        private decimal mdbVal2Field;
        
        private int mdbInc2Field;
        
        private int mdbTub2Field;
        
        private decimal mdbVal3Field;
        
        private int mdbInc3Field;
        
        private int mdbTub3Field;
        
        private decimal mdbVal4Field;
        
        private int mdbInc4Field;
        
        private int mdbTub4Field;
        
        private decimal mdbVal5Field;
        
        private int mdbInc5Field;
        
        private int mdbTub5Field;
        
        private decimal mdbVal6Field;
        
        private int mdbInc6Field;
        
        private int mdbTub6Field;
        
        private decimal cashlessField;
        
        private decimal totalField;
        
        private decimal changeField;
        
        private int salesField;
        
        private int consumabileField;
        
        private string hopperGettoneField;
        
        private decimal vend1PrcField;
        
        private int qtyV1Field;
        
        private decimal vend2PrcField;
        
        private int qtyV2Field;
        
        private int ticketField;
        
        private decimal priceField;
        
        private int bns1Field;
        
        private int bns2Field;
        
        private int bNS_1Field;
        
        private int bNS_2Field;
        
        private int bns5Field;
        
        private int bns10Field;
        
        private int bns20Field;
        
        private int tokenField;
        
        private decimal contMonVisoField;
        
        private decimal mechValueField;
        
        private decimal cashlessNayaxField;
        
        private decimal cashlessAppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MandtGw
        {
            get
            {
                return this.mandtGwField;
            }
            set
            {
                this.mandtGwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CodeMa
        {
            get
            {
                return this.codeMaField;
            }
            set
            {
                this.codeMaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OdmTaskPalmare
        {
            get
            {
                return this.odmTaskPalmareField;
            }
            set
            {
                this.odmTaskPalmareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IdTelemetria
        {
            get
            {
                return this.idTelemetriaField;
            }
            set
            {
                this.idTelemetriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DateB
        {
            get
            {
                return this.dateBField;
            }
            set
            {
                this.dateBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TipoDa
        {
            get
            {
                return this.tipoDaField;
            }
            set
            {
                this.tipoDaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CanaleGettone
        {
            get
            {
                return this.canaleGettoneField;
            }
            set
            {
                this.canaleGettoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CanaleProve
        {
            get
            {
                return this.canaleProveField;
            }
            set
            {
                this.canaleProveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Ch1
        {
            get
            {
                return this.ch1Field;
            }
            set
            {
                this.ch1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int Qty1
        {
            get
            {
                return this.qty1Field;
            }
            set
            {
                this.qty1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Ch2
        {
            get
            {
                return this.ch2Field;
            }
            set
            {
                this.ch2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int Qty2
        {
            get
            {
                return this.qty2Field;
            }
            set
            {
                this.qty2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Ch3
        {
            get
            {
                return this.ch3Field;
            }
            set
            {
                this.ch3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int Qty3
        {
            get
            {
                return this.qty3Field;
            }
            set
            {
                this.qty3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal Ch4
        {
            get
            {
                return this.ch4Field;
            }
            set
            {
                this.ch4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int Qty4
        {
            get
            {
                return this.qty4Field;
            }
            set
            {
                this.qty4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal Ch5
        {
            get
            {
                return this.ch5Field;
            }
            set
            {
                this.ch5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int Qty5
        {
            get
            {
                return this.qty5Field;
            }
            set
            {
                this.qty5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal Ch6
        {
            get
            {
                return this.ch6Field;
            }
            set
            {
                this.ch6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int Qty6
        {
            get
            {
                return this.qty6Field;
            }
            set
            {
                this.qty6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal Ch7
        {
            get
            {
                return this.ch7Field;
            }
            set
            {
                this.ch7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int Qty7
        {
            get
            {
                return this.qty7Field;
            }
            set
            {
                this.qty7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal Ch8
        {
            get
            {
                return this.ch8Field;
            }
            set
            {
                this.ch8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int Qty8
        {
            get
            {
                return this.qty8Field;
            }
            set
            {
                this.qty8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public decimal Ch9
        {
            get
            {
                return this.ch9Field;
            }
            set
            {
                this.ch9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int Qty9
        {
            get
            {
                return this.qty9Field;
            }
            set
            {
                this.qty9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public decimal MdbVal2
        {
            get
            {
                return this.mdbVal2Field;
            }
            set
            {
                this.mdbVal2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public int MdbInc2
        {
            get
            {
                return this.mdbInc2Field;
            }
            set
            {
                this.mdbInc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public int MdbTub2
        {
            get
            {
                return this.mdbTub2Field;
            }
            set
            {
                this.mdbTub2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal MdbVal3
        {
            get
            {
                return this.mdbVal3Field;
            }
            set
            {
                this.mdbVal3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public int MdbInc3
        {
            get
            {
                return this.mdbInc3Field;
            }
            set
            {
                this.mdbInc3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public int MdbTub3
        {
            get
            {
                return this.mdbTub3Field;
            }
            set
            {
                this.mdbTub3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public decimal MdbVal4
        {
            get
            {
                return this.mdbVal4Field;
            }
            set
            {
                this.mdbVal4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public int MdbInc4
        {
            get
            {
                return this.mdbInc4Field;
            }
            set
            {
                this.mdbInc4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public int MdbTub4
        {
            get
            {
                return this.mdbTub4Field;
            }
            set
            {
                this.mdbTub4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public decimal MdbVal5
        {
            get
            {
                return this.mdbVal5Field;
            }
            set
            {
                this.mdbVal5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public int MdbInc5
        {
            get
            {
                return this.mdbInc5Field;
            }
            set
            {
                this.mdbInc5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public int MdbTub5
        {
            get
            {
                return this.mdbTub5Field;
            }
            set
            {
                this.mdbTub5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public decimal MdbVal6
        {
            get
            {
                return this.mdbVal6Field;
            }
            set
            {
                this.mdbVal6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public int MdbInc6
        {
            get
            {
                return this.mdbInc6Field;
            }
            set
            {
                this.mdbInc6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public int MdbTub6
        {
            get
            {
                return this.mdbTub6Field;
            }
            set
            {
                this.mdbTub6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public decimal Cashless
        {
            get
            {
                return this.cashlessField;
            }
            set
            {
                this.cashlessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public decimal Change
        {
            get
            {
                return this.changeField;
            }
            set
            {
                this.changeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public int Sales
        {
            get
            {
                return this.salesField;
            }
            set
            {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public int Consumabile
        {
            get
            {
                return this.consumabileField;
            }
            set
            {
                this.consumabileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string HopperGettone
        {
            get
            {
                return this.hopperGettoneField;
            }
            set
            {
                this.hopperGettoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public decimal Vend1Prc
        {
            get
            {
                return this.vend1PrcField;
            }
            set
            {
                this.vend1PrcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public int QtyV1
        {
            get
            {
                return this.qtyV1Field;
            }
            set
            {
                this.qtyV1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public decimal Vend2Prc
        {
            get
            {
                return this.vend2PrcField;
            }
            set
            {
                this.vend2PrcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public int QtyV2
        {
            get
            {
                return this.qtyV2Field;
            }
            set
            {
                this.qtyV2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public int Ticket
        {
            get
            {
                return this.ticketField;
            }
            set
            {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public int Bns1
        {
            get
            {
                return this.bns1Field;
            }
            set
            {
                this.bns1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public int Bns2
        {
            get
            {
                return this.bns2Field;
            }
            set
            {
                this.bns2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public int BNS_1
        {
            get
            {
                return this.bNS_1Field;
            }
            set
            {
                this.bNS_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public int BNS_2
        {
            get
            {
                return this.bNS_2Field;
            }
            set
            {
                this.bNS_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public int Bns5
        {
            get
            {
                return this.bns5Field;
            }
            set
            {
                this.bns5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public int Bns10
        {
            get
            {
                return this.bns10Field;
            }
            set
            {
                this.bns10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public int Bns20
        {
            get
            {
                return this.bns20Field;
            }
            set
            {
                this.bns20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public int Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public decimal ContMonViso
        {
            get
            {
                return this.contMonVisoField;
            }
            set
            {
                this.contMonVisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public decimal MechValue
        {
            get
            {
                return this.mechValueField;
            }
            set
            {
                this.mechValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public decimal CashlessNayax
        {
            get
            {
                return this.cashlessNayaxField;
            }
            set
            {
                this.cashlessNayaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public decimal CashlessApp
        {
            get
            {
                return this.cashlessAppField;
            }
            set
            {
                this.cashlessAppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZpmRfcConsumiTelemetria400Response
    {
        
        private ZgeTelError erroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZgeTelError Errore
        {
            get
            {
                return this.erroreField;
            }
            set
            {
                this.erroreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZpmRfcConsumiTelemetria400Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReference.ZpmRfcConsumiTelemetria400 ZpmRfcConsumiTelemetria400;
        
        public ZpmRfcConsumiTelemetria400Request()
        {
        }
        
        public ZpmRfcConsumiTelemetria400Request(ServiceReference.ZpmRfcConsumiTelemetria400 ZpmRfcConsumiTelemetria400)
        {
            this.ZpmRfcConsumiTelemetria400 = ZpmRfcConsumiTelemetria400;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZpmRfcConsumiTelemetria400Response1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ServiceReference.ZpmRfcConsumiTelemetria400Response ZpmRfcConsumiTelemetria400Response;
        
        public ZpmRfcConsumiTelemetria400Response1()
        {
        }
        
        public ZpmRfcConsumiTelemetria400Response1(ServiceReference.ZpmRfcConsumiTelemetria400Response ZpmRfcConsumiTelemetria400Response)
        {
            this.ZpmRfcConsumiTelemetria400Response = ZpmRfcConsumiTelemetria400Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ZPM_RFC_CONSUMI_TELEMETRIA_400Channel : ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ZPM_RFC_CONSUMI_TELEMETRIA_400Client : System.ServiceModel.ClientBase<ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400>, ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400
    {
        
        public ZPM_RFC_CONSUMI_TELEMETRIA_400Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ZpmRfcConsumiTelemetria400Response1> ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400.ZpmRfcConsumiTelemetria400Async(ServiceReference.ZpmRfcConsumiTelemetria400Request request)
        {
            return base.Channel.ZpmRfcConsumiTelemetria400Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ZpmRfcConsumiTelemetria400Response1> ZpmRfcConsumiTelemetria400Async(ServiceReference.ZpmRfcConsumiTelemetria400 ZpmRfcConsumiTelemetria400)
        {
            ServiceReference.ZpmRfcConsumiTelemetria400Request inValue = new ServiceReference.ZpmRfcConsumiTelemetria400Request();
            inValue.ZpmRfcConsumiTelemetria400 = ZpmRfcConsumiTelemetria400;
            return ((ServiceReference.ZPM_RFC_CONSUMI_TELEMETRIA_400)(this)).ZpmRfcConsumiTelemetria400Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
